microsoft/HydraLab

- common/src/main/java/com/microsoft/hydralab/common/management/AppiumServerManager.java
> Fix typo in AppiumServerManager.java

- CONTRIBUTING.md
- README.md
Add step 3 and correct the wiki link
> Update README.md: correct link and update the content

- agent/src/main/java/com/microsoft/hydralab/agent/runner/TestRunner.java
- common/src/main/java/com/microsoft/hydralab/common/management/impl/AndroidDeviceManager.java
> Remove the launcher unset operation in device level and move it to test task level

- vsts_extension/Tasks/HydraLabDeployTest/hydra-lab-deploy-test.ts
- vsts_extension/Tasks/HydraLabDeployTest/task.json
- vsts_extension/vss-extension.json
> Upgrade plugins to adapt to grant permission and device action

- agent/src/main/java/com/microsoft/hydralab/agent/config/AppConfiguration.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/espresso/EspressoRunner.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/espresso/EspressoTestInfoProcessorListener.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/smart/SmartRunner.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/smart/SmartTestUtil.java
- agent/src/main/java/com/microsoft/hydralab/agent/service/AgentManageService.java
- agent/src/main/java/com/microsoft/hydralab/agent/service/AgentWebSocketClientService.java
- agent/src/main/java/com/microsoft/hydralab/agent/service/TestTaskEngineService.java
- center/src/main/java/com/microsoft/hydralab/center/controller/AuthController.java
- center/src/main/java/com/microsoft/hydralab/center/controller/DeviceGroupController.java
- center/src/main/java/com/microsoft/hydralab/center/service/DeviceAgentManagementService.java
- center/src/main/java/com/microsoft/hydralab/center/service/DeviceGroupService.java
- center/src/main/java/com/microsoft/hydralab/center/service/TestTaskService.java
- center/src/test/java/com/microsoft/hydralab/center/service/DeviceGroupServiceTest.java
- common/src/main/java/com/microsoft/hydralab/common/entity/agent/SmartTestParam.java
- common/src/main/java/com/microsoft/hydralab/common/screen/PhoneAppScreenRecorder.java
- common/src/main/java/com/microsoft/hydralab/common/util/ADBOperateUtil.java
- common/src/main/java/com/microsoft/hydralab/common/util/Const.java
- common/src/test/java/com/microsoft/hydralab/common/util/SerializeUtilTest.java
- sdk/src/main/java/com/microsoft/hydralab/appium/ThreadParam.java
[x] Added refactoring and code clean up for java files
> Added refactoring and code clean up for java files

- center/src/main/java/com/microsoft/hydralab/center/service/AgentManageService.java
- center/src/main/java/com/microsoft/hydralab/center/util/CenterConstant.java
> bugfix: create File error on linux

- agent/src/main/java/com/microsoft/hydralab/agent/runner/TestRunner.java
- common/src/main/java/com/microsoft/hydralab/common/entity/common/TestRun.java
- common/src/main/java/com/microsoft/hydralab/performance/PerformanceTestManagementService.java
- sdk/src/main/java/com/microsoft/hydralab/agent/runner/ITestRun.java
- sdk/src/main/java/com/microsoft/hydralab/agent/runner/TestRunThreadContext.java
No impact to any existing logic, only add new definition for future refactoring
> Add TestRunThreadContext and move ITestRun to the same package.

- center/deploy_startup/custom.ini
- center/deploy_startup/defaults.ini
- center/deploy_startup/nginx.conf
- center/src/main/java/com/microsoft/hydralab/center/interceptor/BaseInterceptor.java
Add oauth for grafana;
Disable anonymous login of grafana;
Remove nginx setting for prometheus/pushgateway;
> Grafana AAD OAuth login

- agent/src/main/java/com/microsoft/hydralab/agent/config/AppConfiguration.java
- agent/src/main/java/com/microsoft/hydralab/agent/service/AgentWebSocketClientService.java
- agent/src/main/resources/application.yml
- center/Dockerfile
- center/deploy_startup/prometheus.yml
- center/deploy_startup/pushgateway_auth.yml
- center/deploy_startup/start.sh
- center/src/main/java/com/microsoft/hydralab/center/config/AppConfig.java
- center/src/main/java/com/microsoft/hydralab/center/service/DeviceAgentManagementService.java
- center/src/main/resources/application-test.yml
- center/src/main/resources/application.yml
- center/src/test/java/com/microsoft/hydralab/center/service/AgentManageServiceTest.java
- common/src/main/java/com/microsoft/hydralab/common/entity/common/AgentMetadata.java
- common/src/main/java/com/microsoft/hydralab/common/monitor/MetricPushGateway.java
Added a task in release pipeline as well to substitute the secrets in config files.
> Add basic auth for pushgateway

- common/src/main/java/com/microsoft/hydralab/performance/PerformanceTestManagementService.java
- common/src/main/java/com/microsoft/hydralab/performance/inspectors/WindowsMemoryInspector.java
- common/src/main/java/com/microsoft/hydralab/performance/parsers/AndroidBatteryInfoResultParser.java
- common/src/main/java/com/microsoft/hydralab/performance/parsers/WindowsMemoryResultParser.java
- sdk/src/main/java/com/microsoft/hydralab/performance/IPerformanceInspectionService.java
- sdk/src/main/java/com/microsoft/hydralab/performance/PerformanceInspection.java
- sdk/src/main/java/com/microsoft/hydralab/performance/PerformanceInspectionResult.java
- sdk/src/main/java/com/microsoft/hydralab/performance/PerformanceInspectionService.java
- sdk/src/main/java/com/microsoft/hydralab/performance/PerformanceInspector.java
- sdk/src/main/java/com/microsoft/hydralab/performance/PerformanceResultParser.java
- sdk/src/main/java/com/microsoft/hydralab/performance/PerformanceTestResult.java
- sdk/src/test/java/com/microsoft/hydralab/performanc/PerformanceInspectionServiceTest.java
- Add performance result parsers
- Add reset in performance inspection
- Enrich PerformanceInspectionResult
- Implement inspection strategy
- Compatible with future UI visualization and latency test requirements
> [Perf] Add result parser for performance testing

- common/src/main/java/com/microsoft/hydralab/performance/Entity/WindowsBatteryParsedData.java
- common/src/main/java/com/microsoft/hydralab/performance/Entity/WindowsMemoryParsedData.java
- common/src/main/java/com/microsoft/hydralab/performance/parsers/WindowsBatteryResultParser.java
- common/src/main/java/com/microsoft/hydralab/performance/parsers/WindowsMemoryResultParser.java
- common/src/main/resources/WindowsMemoryInspector.ps1
**Changes**
- Implement WindowsMemoryResultParser, WindowsMemoryMetrics
- Implement WindowsBatteryResultParser, WindowsBatteryMetrics
- Refine WindowsMemoryInspector.ps1
**Next**
- Need to verify if the agent configured with elevated privileges can bypass the UAC popup without changing the UAC configuration.
- Add a new method in ShellUtils to run the admin command if the above one is not feasible.
- Make memory & battery test work with more processes of other Windows apps.
> [Perf] Implement WindowsMemoryResultParser, WindowsBatteryResultParser and refine WindowsMemoryInspector.ps1

- .gitignore
- azure-pipelines-ci.yml
- common/build.gradle
- common/src/main/java/com/microsoft/hydralab/common/util/blob/BlobStorageClient.java
- common/src/test/java/com/microsoft/hydralab/common/util/blob/BlobStorageClientTest.java
Tested with UT BlobStorageClientTest (with connectionString set to a blob string), and saw the following file is uploaded:
> [Bugfix] Create the blob container if it doesn't exist when uploading

- center/deploy_startup/defaults.ini
> Fix grafana redirect protocol

- common/src/main/java/com/microsoft/hydralab/common/management/impl/WindowsDeviceManager.java
- common/src/main/java/com/microsoft/hydralab/common/util/ThreadPoolUtil.java
> Bugfix: set the pc screenshot file to avoid NPE

- react/src/component/AuthView.jsx
- react/src/component/DeviceGroupView.jsx
> Mitigate the secret display issue, not a final fix for the potential security risk

- agent/agent_installer/Windows/Android/installer.ps1
- agent/agent_installer/Windows/restartAgent_WindowsService.bat
- agent/agent_installer/Windows/restartAgent_WindowsTaskScheduler.bat
E2E -> Restart Agent by Task Scheduler
Others -> Restart Agent by Windows Service
User will choose if E2E needed and we use 2 ways to setup restart flow
> Update Installer to fix 2 ways of Restart Agent

- agent/src/main/java/com/microsoft/hydralab/agent/runner/appium/AppiumListener.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/espresso/EspressoRunner.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/espresso/EspressoTestInfoProcessorListener.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/monkey/AppiumMonkeyRunner.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/smart/SmartRunner.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/t2c/T2CRunner.java
- Espresso test
- Appium money test
- Smart test
- T2C test
> [Perf]Support performance lifecycle strategy for more test runners

- agent/src/main/java/com/microsoft/hydralab/agent/config/AppConfiguration.java
- common/src/main/java/com/microsoft/hydralab/common/management/DeviceManager.java
- common/src/main/java/com/microsoft/hydralab/common/management/listener/impl/PreInstallListener.java
- common/src/main/java/com/microsoft/hydralab/common/util/Const.java
> Rename preInstallPolicy to preInstallFailurePolicy

- center/src/main/java/com/microsoft/hydralab/center/service/DeviceAgentManagementService.java
> delete redundant validation

- agent/one-line-installer-windows.ps1
One line installer for windows agent.
Android Agent only.
Non-E2E Agent only.
> One line installer for windows agent

- react/src/component/PerfTestDashboard.jsx
> Fix performance report UI

- react/src/component/RunnerView.jsx
Test Your App sounds more friendly and more adaptive
> Update Runner page title

- react/src/component/PerfTestDashboard.jsx
Fix perf dashboard null pointer exception
> [Perf] Fix perf dashboard null pointer exception

- common/src/main/java/com/microsoft/hydralab/common/management/device/impl/WindowsTestDeviceManager.java
- taps_to_cases/runner/src/main/java/com/microsoft/hydralab/t2c/runner/T2CAppiumUtils.java
- taps_to_cases/runner/src/main/java/com/microsoft/hydralab/t2c/runner/controller/BaseDriverController.java
> Add more t2c log

- taps_to_cases/runner/src/main/java/com/microsoft/hydralab/t2c/runner/finder/AndroidElementFinder.java
- taps_to_cases/runner/src/main/java/com/microsoft/hydralab/t2c/runner/finder/EdgeElementFinder.java
- taps_to_cases/runner/src/main/java/com/microsoft/hydralab/t2c/runner/finder/WindowsElementFinder.java
In different platforms, we use different order to find element in T2C runner:
1. For windows, use xpath -> element's text -> automationId
2. For android, use xpath -> a11y id -> element's id -> element's text
3. For edge, use xpath -> element's text -> automationId
> Use xpath to find element in first

- agent/Dockerfile
- agent/src/main/java/com/microsoft/hydralab/agent/AgentApplication.java
- agent/src/main/resources/application.yml
No port for agent service. No port, no conflict.
> Enable no port mode for agent service

- center/src/main/java/com/microsoft/hydralab/center/controller/TestDetailController.java
- react/src/component/PerfTestDashboard.jsx
- Add multi-select for perf dashboard 
- Fix CORS error
> [Perf] Add multi-select for perf dashboard

- azure-pipelines-ci.yml
- build.gradle
1. Package jar into installer.zip
2. Set the versionCode of jars built from main branch
CI updates. No need to test.
> Package jar into installer.zip

- common/src/main/java/com/microsoft/hydralab/performance/entity/AndroidBatteryInfo.java
- common/src/main/java/com/microsoft/hydralab/performance/entity/AndroidMemoryInfo.java
- common/src/main/java/com/microsoft/hydralab/performance/entity/WindowsBatteryParsedData.java
- common/src/main/java/com/microsoft/hydralab/performance/entity/WindowsMemoryParsedData.java
- common/src/main/java/com/microsoft/hydralab/performance/parsers/AndroidBatteryInfoResultParser.java
- common/src/main/java/com/microsoft/hydralab/performance/parsers/AndroidMemoryInfoResultParser.java
- common/src/main/java/com/microsoft/hydralab/performance/parsers/WindowsBatteryResultParser.java
- common/src/main/java/com/microsoft/hydralab/performance/parsers/WindowsMemoryResultParser.java
- common/src/test/java/com/microsoft/hydralab/common/performance/AndroidBatteryInfoResultParserTest.java
Change the package name form Entity to entity
> Pretty format: package name Entity -> entity

- README.md
Add HCG as the Microsoft Give Sponsor of Hydra Lab
> Add HCG as the Microsoft Give Sponsor of Hydra Lab

- center/src/main/java/com/microsoft/hydralab/center/config/RestTemplateConfig.java
- center/src/main/java/com/microsoft/hydralab/center/util/AuthUtil.java
- common/src/main/java/com/microsoft/hydralab/common/util/RestTemplateConfig.java
Remove configuration annotation that creates useless beans
> Remove configuration annotation that creates useless beans

- agent/src/main/java/com/microsoft/hydralab/agent/runner/TestRunner.java
> Retry if install failed

- docs/index.md
mid-2021
As per https://www.thefreedictionary.com/mid-
*If this introduces a breaking change for Hydra Lab users and requires a migration process, please describe the impact and migration path for existing applications below.*
A few words to explain your changes:
Does this close any currently open issues? Issue ID: #
*If this is a relatively large or complex change, kick off the discussion by drawing the tech design with PlantUML and explaining why you chose the solution you did and what alternatives you considered, etc...*
> Added Hypen

- common/src/main/java/com/microsoft/hydralab/common/util/ADBOperateUtil.java
*If this introduces a breaking change for Hydra Lab users and requires a migration process, please describe the impact and migration path for existing applications below.*
A few words to explain your changes:
Add install failover strategy, use adb install when adb shell pm install fails. Our partner reported this recently.
Does this close any currently open issues? Issue ID: #
@zhou9584 could you help test it?
*If this is a relatively large or complex change, kick off the discussion by drawing the tech design with PlantUML and explaining why you chose the solution you did and what alternatives you considered, etc...*
> add install failover strategy

- common/src/main/java/com/microsoft/hydralab/common/util/ShellUtils.java
> Compat redicting output for shell command line

- agent/agent_installer/MacOS/iOS/installer.sh
Add command line tool dependency for macOS agent
Issue ID: #
> Add command line tool dependency for macOS agent

- README.md
- README.zh-CN.md
Update README of both English and Chinese versions for uber image part.
> Update uber image part in README of both English and Chinese versions

- README.md
- README.zh-CN.md
- center/application-sample.yml
- center/src/main/resources/application-release.yml
- center/src/main/resources/application.yml
- center/uber_image/Dockerfile
Update README for outdated content removal;
- Change center storage type in default profile;
- Update README for outdated content removal;
> Change center storage type in default profile, update README for outdated content removal.

- gradle_plugin/build.gradle
- gradle_plugin/src/main/groovy/com/microsoft/hydralab/utils/HydraLabClientUtils.java
Issue ID: #382
Removed log commands for adding build tags, as it's currently of no usage and limited in ADO pipeline.
Tested locally, the log commands have been removed already.
> Remove log commands for adding build tags.

- agent/src/main/java/com/microsoft/hydralab/agent/runner/espresso/EspressoRunner.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/monkey/AdbMonkeyRunner.java
- common/src/main/java/com/microsoft/hydralab/common/util/ADBOperateUtil.java
There may not be output when running instrument test. If the test time of a case > 120s, there would be a exception.
Issue ID:  #
> BugFix: add parameter to set the response timeout value

- README.md
- README.zh-CN.md
Elaborate wiki content to speed up setup process
> Elaborate wiki content to speed up setup process

- .gitignore
- center/Dockerfile
- center/deploy_startup/custom.ini
- center/deploy_startup/start.sh
- Move some customized Grafana config to custom.ini;
- Add docker config within the same dockerfile of release;
- Modify related release pipeline to add center image publish steps;
- Update wiki for center image:
- [Deploy Center Docker Container](https://github.com/microsoft/HydraLab/wiki/Deploy-Center-Docker-Container)
- [Deploy Agent Docker Container](https://github.com/microsoft/HydraLab/wiki/Deploy-Agent-Docker-Container)
Ran locally, and visit the front end to verify the …
> Enable docker startup setting within the same Dockerfile for release

- common/src/main/java/com/microsoft/hydralab/common/management/device/impl/AndroidTestDeviceManager.java
- common/src/main/java/com/microsoft/hydralab/common/screen/PhoneAppScreenRecorder.java
> Bugfix: update app check command

- taps_to_cases/runner/src/main/java/com/microsoft/hydralab/t2c/runner/RobotUtils.java
- taps_to_cases/runner/src/main/java/com/microsoft/hydralab/t2c/runner/controller/EdgeDriverController.java
- taps_to_cases/runner/src/main/java/com/microsoft/hydralab/t2c/runner/controller/WindowsDriverController.java
Issue ID: #
Run the T2C test with input actions in SampleT2CTest.java
> [T2C] Fix 'Send Keys' and 'Input Text'.

- common/src/main/java/com/microsoft/hydralab/common/entity/common/EntityFileRelation.java
- common/src/main/java/com/microsoft/hydralab/common/repository/EntityFileRelationRepository.java
- common/src/main/java/com/microsoft/hydralab/common/util/AttachmentService.java
> BugFix: Add fileOrder filed to sort attachments

- gradle_plugin/build.gradle
Hydra Lab gradle plugin upgrade to 1.1.7.
No change to code.
> Upgrade version of plugin to 1.1.7

- center/src/main/java/com/microsoft/hydralab/center/service/TestDataService.java
- common/src/main/java/com/microsoft/hydralab/performance/parsers/AndroidMemoryInfoResultParser.java
- react/src/component/PerfTestDashboard.jsx
- react/src/component/TestReportView.jsx
#TODO  
Show perf history with multi-page rather than only 10 dots.
Issue ID: #
Run the front-end project and the history chart can be seen at the portal
> [Perf] Add performance history chart

- center/src/main/java/com/microsoft/hydralab/center/service/DeviceAgentManagementService.java
> Update the verify rule of T2C test

- agent/src/main/java/com/microsoft/hydralab/agent/config/AppConfiguration.java
Enable the EnvCapabilityDiscoveryService to scan the env capabilities
Issue ID: #
UT already exists in com.microsoft.hydralab.agent.environment.EnvCapabilityDiscoveryServiceTest
> Enable EnvCapabilityDiscoveryService capability scanning in configuration 

- center/src/main/java/com/microsoft/hydralab/center/service/StorageTokenManageService.java
> Update log to clarify error

- gradle_plugin/build.gradle
- gradle_plugin/src/main/groovy/com/microsoft/hydralab/utils/HydraLabClientUtils.java
- gradle_plugin/template/gradle.properties
- Re-init static fields to overlap the previous values from run of this task
- Upgrade version to 1.1.8.
- 
Tested locally.
> Re-init static fields to overlap the previous values from run of this task

- agent/src/main/java/com/microsoft/hydralab/agent/config/AppConfiguration.java
- agent/src/main/java/com/microsoft/hydralab/agent/config/DeviceDriverConfig.java
deviceDriverManager -> deviceStatusListenerManager -> deviceStabilityMonitor -> teamInfo of agentuser -> agentWebSocketClient
We need to make sure the drivers of deviceDriverManager has been added before load the bean of  agentWebSocketClient
> Bugfix: add drivers when create bean of DeviceDriverManager

- agent/src/main/java/com/microsoft/hydralab/agent/util/FileLoadUtil.java
> Fix timeout for installing win app

- agent/src/main/java/com/microsoft/hydralab/agent/runner/t2c/T2CRunner.java
> Bugfix: Cannot download file when clicking the Device Log button of T2C task report

- center/src/main/java/com/microsoft/hydralab/center/service/TestFileSetService.java
- center/src/main/resources/application.yml
- common/src/main/java/com/microsoft/hydralab/common/file/StorageServiceClientProxy.java
- common/src/main/java/com/microsoft/hydralab/common/file/impl/local/LocalStorageClientAdapter.java
- common/src/main/java/com/microsoft/hydralab/common/file/impl/local/LocalStorageProperty.java
- common/src/main/java/com/microsoft/hydralab/common/util/AttachmentService.java
- Add criteria of file limit for test file set entities;
- Add fileLimitDay attribute in yml;
> Fix: portal package list may display outdated packages

- common/src/main/java/com/microsoft/hydralab/common/screen/PhoneAppScreenRecorder.java
> Bugfix: record phone video failed

- agent/src/main/java/com/microsoft/hydralab/agent/util/FileLoadUtil.java
- common/src/test/java/com/microsoft/hydralab/common/util/FileUtilTest.java
…ultiple attachments in the same folder
> Bugfix: Save the loaded folder to WhiteList to avoid exception when multiple attachments in the same folder

- agent/agent_installer/MacOS/iOS/installer.sh
*If this introduces a breaking change for Hydra Lab users and requires a migration process, please describe the impact and migration path for existing applications below.*
A few words to explain your changes:
I've update the https://github.com/microsoft/HydraLab/wiki/Test-agent-setup-on-MacOS to reflect the change.
Does this close any currently open issues? Issue ID: #
*If this is a relatively large or complex change, kick off the discussion by drawing the tech design with PlantUML and explaining why you chose the solution you did and what alternatives you considered, etc...*
> Generalize the application config file name in installer.sh for MacOS agent setup

- agent/src/main/java/com/microsoft/hydralab/agent/service/TestTaskEngineService.java
> Bugfix: update condition of upload test results

- agent/agent_installer/Windows/restartAgent.bat
- agent/agent_installer/Windows/restartAgent_WindowsService.bat
- agent/agent_installer/Windows/restartAgent_WindowsTaskScheduler.bat
> Bugfix: remove space in command line

- center/src/main/java/com/microsoft/hydralab/center/controller/DeviceGroupController.java
Restrict group creation permission to team admin only.
> Restrict group creation permission to team admin only

- react/src/component/PerfTestDashboard.jsx
> [Fix] Fix iOS perf dashboard

- agent/application-sample.yml
- center/src/main/java/com/microsoft/hydralab/center/service/AgentManageService.java
> BugFix: update sample yml and yml downloaded from center

- agent/src/main/java/com/microsoft/hydralab/agent/runner/DeviceTaskControlExecutor.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/TestRunner.java
- agent/src/main/java/com/microsoft/hydralab/agent/service/TestTaskEngineService.java
- agent/src/test/java/com/microsoft/hydralab/agent/runner/TestRunnerTest.java
- common/src/main/java/com/microsoft/hydralab/common/entity/common/TestRunDevice.java
**A few words to explain your changes**:  Move the device level logger to the test run device entity
> Add the logger to TestRunDevice to get prepared for next stage refactor

- agent/src/main/java/com/microsoft/hydralab/agent/runner/t2c/T2CRunner.java
> Bugfix: init the deviceCountMap variable everytime

- common/src/main/java/com/microsoft/hydralab/common/management/device/impl/DeviceDriverManager.java
> Bugfix: get AppiumServerManager from the first driver

- common/src/main/java/com/microsoft/hydralab/common/entity/common/PerformanceTestResultEntity.java
- common/src/main/java/com/microsoft/hydralab/performance/PerformanceTestManagementService.java
- common/src/test/java/com/microsoft/hydralab/common/performance/PerformanceTestResultEntityTest.java
> [Fix][Perf] Fix NullPointerException of the performance test result entity

- agent/src/main/java/com/microsoft/hydralab/agent/service/TestTaskEngineService.java
- common/src/main/java/com/microsoft/hydralab/common/logger/impl/IOSLogCollector.java
- common/src/main/java/com/microsoft/hydralab/common/screen/IOSAppiumScreenRecorderForWindows.java
- common/src/main/java/com/microsoft/hydralab/common/util/IOSUtils.java
> BugFix: wait for the record process finish to avoid merge error

- react/.gitignore
- react/webpack.config.js
- react/webpack.config.json
> Split dev server pointer config to another file

- agent/src/main/java/com/microsoft/hydralab/agent/runner/espresso/EspressoTestInfoProcessorListener.java
Add error log output to test info listener.
> Fix: print Espresso test error log with log level ERROR

- common/src/main/java/com/microsoft/hydralab/performance/entity/WindowsBatteryParsedData.java
- common/src/main/java/com/microsoft/hydralab/performance/entity/WindowsMemoryParsedData.java
> [Perf] Implement getSummaryType() for Windows platform

- react/src/component/PerfTestDashboard.jsx
1. Support multi-app on performance dashboard.
2. Add a separate section for performance test history to make the perf dashboard easier to read.
1. Select app
2. Perf history section
> [Perf] Support multi-app on performance dashboard

- taps_to_cases/runner/src/main/java/com/microsoft/hydralab/t2c/runner/T2CJsonParser.java
Fix a bug that T2C runner will ignore init actions when it is not running on iOS devices.
> T2C runner should init with init actions

- agent/src/main/java/com/microsoft/hydralab/agent/runner/TestRunDeviceOrchestrator.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/TestRunner.java
- common/src/main/java/com/microsoft/hydralab/common/management/device/DeviceDriver.java
- common/src/main/java/com/microsoft/hydralab/common/management/device/impl/AbstractDeviceDriver.java
- common/src/main/java/com/microsoft/hydralab/common/management/device/impl/AndroidDeviceDriver.java
- common/src/main/java/com/microsoft/hydralab/common/management/device/impl/DeviceDriverManager.java
- common/src/main/java/com/microsoft/hydralab/common/management/device/impl/IOSDeviceDriver.java
- common/src/main/java/com/microsoft/hydralab/common/management/device/impl/WindowsDeviceDriver.java
- common/src/main/java/com/microsoft/hydralab/common/screen/PhoneAppScreenRecorder.java
> Bugfix: send KEYCODE_MENU event may cause issue when taking screenshot

- azure-pipelines-ci.yml
> Bugfix: Combine 2 steps to 1 to reduce mkdir operation

- react/src/component/TasksView.jsx
> Bugfix: Set the max length of suite name to optimize front-end page

- azure-pipelines-ci.yml
> Bugfix: check the file is exist or not before cp

- react/src/component/DeviceAgentsView.jsx
**A few words to explain your changes**:  Leverage recharts and lodash to group and count the data, and show them as pie charts.
> Add device and agent stat pie charts

- common/src/main/java/com/microsoft/hydralab/performance/PerformanceTestManagementService.java
Trigger a test run with perf trategy
> [Perf] Fix perf wrong device ID bug & add logs

- agent/src/main/java/com/microsoft/hydralab/agent/runner/TestRunner.java
- common/src/main/java/com/microsoft/hydralab/performance/PerformanceTestManagementService.java
- common/src/main/java/com/microsoft/hydralab/performance/inspectors/AndroidBatteryInfoInspector.java
- common/src/main/java/com/microsoft/hydralab/performance/inspectors/AndroidMemoryInfoInspector.java
- common/src/main/java/com/microsoft/hydralab/performance/inspectors/EventTimeInspector.java
- common/src/main/java/com/microsoft/hydralab/performance/inspectors/IOSEnergyGaugeInspector.java
- common/src/main/java/com/microsoft/hydralab/performance/inspectors/IOSMemoryPerfInspector.java
- common/src/main/java/com/microsoft/hydralab/performance/inspectors/WindowsBatteryInspector.java
- common/src/main/java/com/microsoft/hydralab/performance/inspectors/WindowsMemoryInspector.java
- common/src/main/java/com/microsoft/hydralab/performance/parsers/AndroidBatteryInfoResultParser.java
- common/src/main/java/com/microsoft/hydralab/performance/parsers/AndroidMemoryInfoResultParser.java
- common/src/main/java/com/microsoft/hydralab/performance/parsers/EventTimeResultParser.java
- common/src/main/java/com/microsoft/hydralab/performance/parsers/IOSEnergyGaugeResultParser.java
- common/src/main/java/com/microsoft/hydralab/performance/parsers/IOSMemoryPerfResultParser.java
- common/src/main/java/com/microsoft/hydralab/performance/parsers/WindowsBatteryResultParser.java
- common/src/main/java/com/microsoft/hydralab/performance/parsers/WindowsMemoryResultParser.java
- common/src/test/java/com/microsoft/hydralab/common/performance/AndroidBatteryInfoResultParserTest.java
- sdk/src/main/java/com/microsoft/hydralab/agent/runner/ITestRun.java
- sdk/src/main/java/com/microsoft/hydralab/performance/PerformanceInspector.java
- sdk/src/main/java/com/microsoft/hydralab/performance/PerformanceResultParser.java
- Fix file path exceeds MAX_PATH bug
- Add more logs for perf test
> [Perf] Fix file path exceeds MAX_PATH bug & Add more logs for perf test

- agent/one-line-installer-windows.ps1
Since some online change, One Line Installer has broke.
Update and fix issues.
> fix one liner installer issue because of online change

- center/src/main/java/com/microsoft/hydralab/center/controller/DeviceGroupController.java
Fix log error of device group creation, so that no confusion could be made.
> Fix log error of device group creation

- center/src/main/java/com/microsoft/hydralab/center/config/SwaggerConfig.java
Upgrade swagger version for URSA scanning
Tested locally, swagger pages can successfully be opened.
> Upgrade swagger version for URSA scanning

- react/src/component/TasksView.jsx
**Linked GitHub issue ID**: #497 
**A few words to explain your changes**:  Revert inserted running task list, to make sure the overall tasks are in the sequence of time DESC.
Locally built and tested, sequence disorder is fixed.
> Bugfix: task list disorder caused by reversed running task order in the task list

- center/src/main/java/com/microsoft/hydralab/center/service/TestDataService.java
**A few words to explain your changes**:  Temporarily disable checks on user's auth in corresponding teams to unblock users from accessing test results.
> Temporarily disable checks on user's auth in corresponding teams

- center/build.gradle
- center/src/main/java/com/microsoft/hydralab/center/config/SwaggerConfig.java
- center/src/main/java/com/microsoft/hydralab/center/config/WebMvcConfiguration.java
- center/src/main/resources/application.yml
- Upgrade swagger from version 2 to 3;
- Alter related dependency libs and configurations;
- Disable default swagger page with sample data;
> Upgrade swagger from version 2 to 3

- react/src/component/PerfTestDashboard.jsx
Export performance data to csv
> [Perf] [Front-end] Export performance data to csv

- agent/src/main/java/com/microsoft/hydralab/agent/runner/TestRunDeviceOrchestrator.java
- common/src/main/java/com/microsoft/hydralab/common/management/AppiumServerManager.java
- common/src/main/java/com/microsoft/hydralab/common/screen/IOSAppiumScreenRecorderForMac.java
> Bugfix: isDriverAlive method can't verify the staus of iosDriver

- gradle/wrapper/gradle-wrapper.properties
**A few words to explain your changes**:  Upgrade to gradle 6.9.4 to leverage fix and optimizations in gradle build
> Upgrade to gradle 6.9.4 to leverage fix and optimizations in gradle build

- center/src/main/java/com/microsoft/hydralab/center/config/AppConfig.java
- center/src/main/java/com/microsoft/hydralab/center/config/WebMvcConfiguration.java
> Bugfix: add SupportedMediaTypes to fastJsonHttpMessageConverter

- center/src/main/java/com/microsoft/hydralab/center/service/TestTaskService.java
> Bugfix: use iterator to avoid ConcurrentModificationException

- agent/src/main/java/com/microsoft/hydralab/agent/runner/ActionExecutor.java
Fix filter for device actions passed from agent init, so that actions with no device type won't be filtered out.
> Fix action executor

- agent/src/main/java/com/microsoft/hydralab/agent/runner/ActionExecutor.java
Fix action executer: remove null filter for device actions
> Fix action executer: remove null filter for device actions

- common/src/main/java/com/microsoft/hydralab/performance/PerformanceTestManagementService.java
Inspector map is missing with hprof type.
> Bugfix: fix hprof mapping missing

- common/src/main/java/com/microsoft/hydralab/common/management/AppiumServerManager.java
- common/src/main/java/com/microsoft/hydralab/common/management/device/impl/IOSDeviceDriver.java
> Bugfix: unlockDevice method would make the phone back to desktop

- common/src/main/java/com/microsoft/hydralab/performance/PerformanceTestManagementService.java
> fix: CP fix for PR #517

- react/src/component/TasksView.jsx
Fix regression caused by reverse due to multiple renders.
Tested locally.
> Fix regression caused by multi-render

- common/src/main/java/com/microsoft/hydralab/common/entity/agent/MobileDevice.java
- common/src/main/java/com/microsoft/hydralab/common/entity/common/PerformanceTestResultEntity.java
- common/src/main/java/com/microsoft/hydralab/common/entity/common/TestRunDeviceCombo.java
- common/src/main/java/com/microsoft/hydralab/common/management/device/impl/AndroidDeviceDriver.java
- common/src/main/java/com/microsoft/hydralab/performance/PerformanceTestManagementService.java
- common/src/test/java/com/microsoft/hydralab/common/performance/PerformanceTestResultEntityTest.java
Run the test and check the performance data in DB
> [Perf] Add model and build number for PerformanceTestResultEntity

- common/src/main/java/com/microsoft/hydralab/common/entity/common/TestTask.java
Fix an data base schema error for vpn attribute
> Fix data schema error

- center/src/main/java/com/microsoft/hydralab/center/controller/TestDetailController.java
- center/src/main/java/com/microsoft/hydralab/center/service/TestDataService.java
- common/src/main/java/com/microsoft/hydralab/common/entity/common/AndroidTestUnit.java
> Add an API to save the different types of suggestion provided by GPT

- center/src/main/java/com/microsoft/hydralab/center/openai/AzureOpenAIServiceClient.java
- center/src/test/java/com/microsoft/hydralab/center/openai/AzureOpenAIServiceClientTest.java
**A few words to explain your changes**:  Provide new UT leveraging mockito and refactor to extract the method
> Provide new UT and refactor to extract the method

- agent/src/main/java/com/microsoft/hydralab/agent/runner/xctest/XCTestRunner.java
> Bugfix: uninstall app before XCTest to clear data

- android_client/app/src/main/AndroidManifest.xml
- android_client/app/src/main/java/com/microsoft/hydralab/android/client/MainActivity.java
- android_client/app/src/main/java/com/microsoft/hydralab/android/client/ScreenRecorderService.java
- common/src/main/java/com/microsoft/hydralab/common/entity/common/TestTaskSpec.java
- common/src/main/java/com/microsoft/hydralab/common/management/listener/impl/PreInstallListener.java
- common/src/main/java/com/microsoft/hydralab/common/network/AndroidNetworkMonitor.java
Fix Network Monitor issue for multi devices
- [x Tests for the changes have been added (for bug fixes / features)
> Fix network adb multi-device issue

- common/src/main/java/com/microsoft/hydralab/common/management/listener/impl/PreInstallListener.java
> Bugfix: try to uninstall first before pre-install

- common/build.gradle
**A few words to explain your changes**:  Update build.gradle to upgrade apk-parse leveraging fixes
The source code lives: https://github.com/hsiafan/apk-parser
> Update build.gradle to upgrade apk-parse leveraging fixes

- .github/pull_request_template.md
Update pull_request_template.md to simplify the PR desc
> Update pull_request_template.md to simplify the PR desc

- center/src/main/java/com/microsoft/hydralab/center/service/DeviceAgentManagementService.java
- taps_to_cases/runner/src/main/java/com/microsoft/hydralab/t2c/runner/T2CJsonParser.java
Results of checking illegal JSON:
> [Fix] Verify T2C case file before testing

- center/src/main/java/com/microsoft/hydralab/center/controller/TestTaskController.java
Fix accessibility of report page with testTaskId. This API is missed as it's placed separately within TestTaskController.
Tested locally
> Fix accessibility of report page with testTaskId

- react/src/component/TasksView.jsx
- Fix: running tasks won't filter result based on selectors.
- Update "End Date" to "Start Date" in header as the actual query value refers to.
Tested locally, now running items with empty package name will be filtered out.
> Fix: running tasks won't filter result based on selectors

- center/src/main/java/com/microsoft/hydralab/center/service/TestDataService.java
> Bugfix: update the test case in key_value table

- common/src/main/java/com/microsoft/hydralab/common/management/AppiumServerManager.java
> Bugfix: re-create iOS-Appium session after 1 day to reduce long latency

- agent/src/main/java/com/microsoft/hydralab/agent/service/AgentWebSocketClientService.java
- agent/src/main/java/com/microsoft/hydralab/agent/service/TestTaskEngineService.java
- agent/src/main/java/com/microsoft/hydralab/agent/util/FileLoadUtil.java
- center/src/main/java/com/microsoft/hydralab/center/service/DeviceAgentManagementService.java
- common/src/main/java/com/microsoft/hydralab/common/entity/common/TestTask.java
- common/src/main/java/com/microsoft/hydralab/common/util/FlowUtil.java
> Bugfix: Handle the exception that throwed by blob when trigger test

- azure-pipelines-ci.yml
> Disable draft PR trigger CI

- README.md
Update README.md to simplify the description and keep content up-to-date and concise.
I've moved some of the detailed content to the following wikis:
- https://github.com/microsoft/HydraLab/wiki/Deploy-Center-Docker-Container
> Update README.md to simplify description and keep content up to date

- react/src/component/DeviceAgentsView.jsx
- react/src/css/deviceAgentsView.css
Show Agent Function Availibilities
> Show Agent Function Availibilities

- agent/src/main/java/com/microsoft/hydralab/agent/util/FileLoadUtil.java
- common/src/main/java/com/microsoft/hydralab/common/management/device/impl/AndroidDeviceDriver.java
- common/src/main/java/com/microsoft/hydralab/common/util/ShellUtils.java
When running multiple identical tasks on an agent at the same time, if the attachment is loaded into the same directory, a situation may arise: the directory is cleaned up after task A ends, and the file has been deleted when task B wants to use the attachment.
> Bugfix: load attachments to distinct folder for each task

- agent/src/main/java/com/microsoft/hydralab/agent/config/AppConfiguration.java
- agent/src/main/java/com/microsoft/hydralab/agent/config/TestRunnerConfig.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/smart/SmartRunner.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/smart/SmartTestUtil.java
- agent/src/main/resources/application.yml
- common/src/main/java/com/microsoft/hydralab/common/entity/agent/LLMProperties.java
- common/src/main/java/com/microsoft/hydralab/common/entity/agent/SmartTestParam.java
- common/src/main/java/com/microsoft/hydralab/common/util/Const.java
Added LLM integration compatibility for smart test in Hydra Lab test runner.
> Make LLM integration compatible in Hydra Lab for smart test triggering.

- agent/src/main/java/com/microsoft/hydralab/agent/config/AppConfiguration.java
- agent/src/main/java/com/microsoft/hydralab/agent/service/AgentWebSocketClientService.java
- center/src/main/java/com/microsoft/hydralab/center/config/AppConfig.java
- center/src/main/java/com/microsoft/hydralab/center/service/DeviceAgentManagementService.java
- center/src/main/resources/application.yml
> Add config property to control error reporter

- common/src/main/java/com/microsoft/hydralab/common/appcenter/AppCenterErrorLogHandler.java
- common/src/test/java/com/microsoft/hydralab/common/appcenter/AppCenterClientTest.java
> Bugfix: update the exception type to error

- agent/src/main/java/com/microsoft/hydralab/agent/config/TestRunnerConfig.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/XmlBuilder.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/espresso/XmlTestRunListener.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/maestro/MaestroListener.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/maestro/MaestroResultReceiver.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/maestro/MaestroRunner.java
- center/src/main/java/com/microsoft/hydralab/center/controller/PackageSetController.java
- common/src/main/java/com/microsoft/hydralab/common/entity/agent/EnvCapability.java
- common/src/main/java/com/microsoft/hydralab/common/entity/common/TestTask.java
- common/src/main/java/com/microsoft/hydralab/common/util/FileUtil.java
- common/src/main/java/com/microsoft/hydralab/common/util/PkgUtil.java
- common/src/test/java/com/microsoft/hydralab/common/util/StringUtilsTest.java
- react/src/component/RunnerView.jsx
- react/src/component/TasksView.jsx
> New Feature: integrate with Maestro

- center/Dockerfile
- center/deploy_startup/ssh_setup.sh
- center/deploy_startup/sshd_config
- center/deploy_startup/start.sh
Reenable SSH for deployment debugging.
> Reenable SSH for deployment debugging

- agent/src/main/resources/logback-common.xml
- agent/src/test/java/com/microsoft/hydralab/agent/exception/ExceptionReporterManagerTest.java
- center/src/main/resources/logback-common.xml
> Bugfix: leverage async appender to avoid blocking thread

- agent/src/main/java/com/microsoft/hydralab/agent/config/AppConfiguration.java
- agent/src/main/java/com/microsoft/hydralab/agent/config/TestRunnerConfig.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/python/PythonRunner.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/smart/SmartTestUtil.java
- common/src/main/java/com/microsoft/hydralab/common/entity/common/TestTask.java
- common/src/main/java/com/microsoft/hydralab/common/exception/handler/ServiceExceptionHandler.java
- common/src/main/java/com/microsoft/hydralab/common/exception/handler/ThreadExceptionHandler.java
- common/src/main/java/com/microsoft/hydralab/common/management/device/impl/WindowsDeviceDriver.java
- common/src/main/java/com/microsoft/hydralab/common/util/AttachmentService.java
- common/src/main/java/com/microsoft/hydralab/common/util/FileUtil.java
- common/src/main/java/com/microsoft/hydralab/common/util/PkgUtil.java
- common/src/main/java/com/microsoft/hydralab/common/util/PythonUtil.java
- common/src/test/java/com/microsoft/hydralab/common/util/FileUtilTest.java
- react/src/component/DeviceAgentsView.jsx
- react/src/component/RunnerView.jsx
- react/src/component/TasksView.jsx
> Feature: add python runner to run python package

- common/src/main/java/com/microsoft/hydralab/common/management/listener/impl/PreInstallListener.java
> Bugfix: try to install pre-app first, if error, uninstall than re-install

- agent/src/main/resources/logback-common.xml
- center/src/main/resources/logback-common.xml
- common/src/main/java/com/microsoft/hydralab/common/management/listener/impl/PreInstallListener.java
**Center, debug mode**
**Agent, Windows Service mode**
> Bugfix: if use use the same naming of logger, the output of the first logger would be dismissed

- gradle_plugin/template/gradle.properties
> Update template comment for latest runner types

- center/deploy_startup/nginx.conf
- common/src/main/java/com/microsoft/hydralab/common/file/impl/local/client/LocalStorageClient.java
- [Nginx auto work process configuration](https://ieevee.com/tech/2020/05/11/nginx-process-auto.html)
- disable the Nginx [proxy_buffering](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffering)
upload files with 4 threads and file size > 400MB in each thread
> Bugfix: update nginx configuration to adapt to upload large files 

- gradle_plugin/src/main/groovy/com/microsoft/hydralab/utils/CommonUtils.java
- gradle_plugin/src/main/groovy/com/microsoft/hydralab/utils/FlowUtil.java
- gradle_plugin/src/main/groovy/com/microsoft/hydralab/utils/HydraLabAPIClient.java
Gradle plugin: extract retry methods of API calling, so that the first failed request attempt would also retry.
> Gradle plugin: extract retry methods of API calling

- center/src/main/java/com/microsoft/hydralab/center/config/WebMvcConfiguration.java
- center/src/main/java/com/microsoft/hydralab/center/controller/AuthController.java
- center/src/main/java/com/microsoft/hydralab/center/interceptor/BaseInterceptor.java
- common/src/main/java/com/microsoft/hydralab/common/util/Const.java
Revert auth-passing logic of swagger API and add it to excluded list for security review and USRA requirement.
Locally test without using auth code. No redirect and page shows directly.
> Revert auth-passing logic of swagger API and add it to excluded list

- agent/agent_installer/Windows/restartAgent.bat
- agent/agent_installer/Windows/restartAgent_WindowsService.bat
- agent/agent_installer/Windows/restartAgent_WindowsTaskScheduler.bat
- agent/src/main/java/com/microsoft/hydralab/agent/scheduled/ScheduledDeviceControlTasks.java
- agent/src/main/java/com/microsoft/hydralab/agent/service/TestTaskEngineService.java
- agent/src/main/java/com/microsoft/hydralab/agent/socket/AgentWebSocketClient.java
- center/src/main/java/com/microsoft/hydralab/center/controller/DeviceGroupController.java
- center/src/main/java/com/microsoft/hydralab/center/service/DeviceAgentManagementService.java
- center/src/main/java/com/microsoft/hydralab/center/socket/CenterDeviceSocketEndpoint.java
- common/src/main/java/com/microsoft/hydralab/common/management/device/impl/AndroidDeviceDriver.java
> Bugfix: shutdown the agent if agent info has been used

- gradle_plugin/build.gradle
- gradle_plugin/src/main/groovy/com/microsoft/hydralab/utils/HydraLabAPIClient.java
Fix gradle plugin Automic error which leads to retry failure.
> Fix gradle plugin Automic error which leads to retry failure

- common/src/main/java/com/microsoft/hydralab/common/appcenter/AppCenterErrorLogHandler.java
- common/src/main/java/com/microsoft/hydralab/common/appcenter/entity/HandledErrorLog.java
> Update HandledErrorLog.java to improve naming

- agent/src/main/java/com/microsoft/hydralab/agent/runner/scanner/ApkCanaryExecutor.java
- agent/src/main/resources/apk_canary/apk_canary_config_template.json
- agent/src/test/java/com/microsoft/hydralab/agent/runner/scanner/ApkCanaryExecutorTest.java
- agent/src/test/resources/MicrosoftLauncherAPKReport.json
- android_client/gradle/wrapper/gradle-wrapper.properties
- azure-pipelines-ci.yml
- build.gradle
- common/src/main/java/com/microsoft/hydralab/common/entity/common/scanner/ApkManifest.java
- common/src/main/java/com/microsoft/hydralab/common/entity/common/scanner/ApkReport.java
- common/src/main/java/com/microsoft/hydralab/common/entity/common/scanner/ApkSizeReport.java
- common/src/main/java/com/microsoft/hydralab/common/entity/common/scanner/BuildInfo.java
> Add APK canary as Android package scanner

- center/src/main/java/com/microsoft/hydralab/center/service/TestDataService.java
- react/src/component/PropertyTable.jsx
- react/src/component/SearchView.jsx
> LLM exception suggestion front end

- agent/src/main/java/com/microsoft/hydralab/agent/runner/scanner/ApkCanaryExecutor.java
- agent/src/main/resources/apk_canary/apk_canary_config_template.json
- agent/src/test/java/com/microsoft/hydralab/agent/runner/scanner/ApkCanaryExecutorTest.java
- agent/src/test/resources/MicrosoftLauncherAPKReport.json
- android_client/gradle/wrapper/gradle-wrapper.properties
- azure-pipelines-ci.yml
- build.gradle
- common/src/main/java/com/microsoft/hydralab/common/entity/common/scanner/ApkManifest.java
- common/src/main/java/com/microsoft/hydralab/common/entity/common/scanner/ApkReport.java
- common/src/main/java/com/microsoft/hydralab/common/entity/common/scanner/ApkSizeReport.java
- common/src/main/java/com/microsoft/hydralab/common/entity/common/scanner/BuildInfo.java
- Add APK canary executor
- Remove resources folder from Jacoco coverage computation base. 
> Add APK canary scanner

- .gitignore
- common/src/main/java/com/microsoft/hydralab/common/entity/common/AppComponent.java
- common/src/main/java/com/microsoft/hydralab/common/entity/common/TestAppContext.java
- common/src/main/java/com/microsoft/hydralab/common/entity/common/UIPage.java
- common/src/main/java/com/microsoft/hydralab/common/util/PkgUtil.java
- common/src/test/java/com/microsoft/hydralab/common/util/PkgUtilTest.java
Added a new TestAppContext class to store all the test app information, and it could act as the context for a test run. Also leverage the APK-parser and PkgUtil and dom to get app component information, serving as the test coverage compute base.
Besides:
- fix many warnings in PkgUtil regarding IO closing and redundant value init.
*If this is a relatively large or complex change, kick it off by drawing the tech design with PlantUML and explaining why you chose the solution you did and what alternatives you …
> TestAppContext and Parser in PkgUtil for Android

- common/src/main/java/com/microsoft/hydralab/common/exception/handler/ServiceExceptionHandler.java
> Bugfix: Return the exception to prevent the front end from not getting the returned data

- agent/src/main/java/com/microsoft/hydralab/agent/runner/smart/SmartRunner.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/smart/SmartTestUtil.java
- center/build.gradle
- center/src/main/java/com/microsoft/hydralab/center/openai/QAGPTService.java
- common/src/main/java/com/microsoft/hydralab/common/entity/agent/SmartTestParam.java
- common/src/main/java/com/microsoft/hydralab/common/util/Const.java
> Feature:  save configuration to file

- agent/src/main/java/com/microsoft/hydralab/agent/runner/smart/SmartRunner.java
Fix crash detection in smart test and add logs
> Fix crash detection in smart test

- center/src/main/java/com/microsoft/hydralab/center/openai/SuggestionService.java
> Bugfix: the file hasn't been saved before generate perf analysis

- center/src/main/java/com/microsoft/hydralab/center/controller/DeviceGroupController.java
- center/src/main/java/com/microsoft/hydralab/center/service/DeviceAgentManagementService.java
- center/src/main/java/com/microsoft/hydralab/center/service/TestTaskService.java
> Bugfix: check the private property with the same method

- agent/src/main/java/com/microsoft/hydralab/agent/runner/TestRunner.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/espresso/EspressoTestInfoProcessorListener.java
> Bugfix: naming the file by pkg name

- react/src/component/TasksView.jsx
> Bugfix: fix long suite name display in front-end

- azure-pipelines-ci.yml
> Bugfix: add if statement to adapt to pull request from fork repo

- agent/src/main/java/com/microsoft/hydralab/agent/runner/TestRunDeviceOrchestrator.java
- agent/src/main/java/com/microsoft/hydralab/agent/scheduled/ScheduledDeviceControlTasks.java
- agent/src/main/java/com/microsoft/hydralab/agent/service/DeviceControlService.java
- agent/src/main/java/com/microsoft/hydralab/agent/service/TestTaskEngineService.java
- agent/src/main/resources/application.yml
- common/src/main/java/com/microsoft/hydralab/common/management/device/DeviceDriver.java
- common/src/main/java/com/microsoft/hydralab/common/management/device/impl/AbstractDeviceDriver.java
- common/src/main/java/com/microsoft/hydralab/common/management/device/impl/AndroidDeviceDriver.java
- common/src/main/java/com/microsoft/hydralab/common/management/device/impl/DeviceDriverManager.java
- common/src/main/java/com/microsoft/hydralab/common/management/device/impl/IOSDeviceDriver.java
- common/src/main/java/com/microsoft/hydralab/common/management/device/impl/WindowsDeviceDriver.java
> Feature: reboot devices regularly

- agent/src/main/java/com/microsoft/hydralab/agent/runner/TestRunner.java
> Fix: smart test timeout didn't set failure count, faultly results in result success

- agent/src/main/java/com/microsoft/hydralab/agent/config/AppConfiguration.java
- agent/src/main/resources/application.yml
- center/src/main/java/com/microsoft/hydralab/center/service/AgentManageService.java
Need to update agents firstly and then enable center https only configuration.
> Bugfix: add configuration for enabling the Https Only option

- center/src/main/java/com/microsoft/hydralab/center/service/TestTaskService.java
> Bugfix: catch the exception when saving to db to avoid queue block

- center/deploy_startup/nginx.conf
> Bugfix: add HSTS header to avoid security issue

- README.md
- agent/src/main/resources/application-docker.yml
Fix: agent docker connection issue, update wiki for Uber image 
> Bugfix: agent docker connection issue, update wiki for Uber image 

- agent/src/main/java/com/microsoft/hydralab/agent/runner/TestRunDeviceOrchestrator.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/espresso/EspressoRunner.java
- common/src/main/java/com/microsoft/hydralab/common/management/device/DeviceDriver.java
- common/src/main/java/com/microsoft/hydralab/common/management/device/impl/AbstractDeviceDriver.java
- common/src/main/java/com/microsoft/hydralab/common/management/device/impl/AndroidDeviceDriver.java
- common/src/main/java/com/microsoft/hydralab/common/management/device/impl/DeviceDriverManager.java
Reinstall test orchestrator with additional param to make sure test orchestrator feature runs well with all versions of Android APIs.
Tested locally with no bug / issue.
> Reinstall test orchestrator with additional param

- react/src/component/TasksView.jsx
> Bugfix: update front page of task list to display the status of analysis task

- center/src/main/java/com/microsoft/hydralab/center/service/TestDataService.java
- common/src/main/java/com/microsoft/hydralab/common/entity/common/Task.java
> Bugfix: Handle deprecated fields to adapt to history versions of plugins

- common/src/main/java/com/microsoft/hydralab/common/entity/common/Task.java
- common/src/test/java/com/microsoft/hydralab/common/util/SerializeUtilTest.java
> Bugfix: Fix the issue caused by serializing

- agent/build.gradle
- android_client/app/build.gradle
- android_client/app/src/main/java/com/microsoft/hydralab/android/client/MainActivity.java
We want to leverage clarity to understand the usage data of Hydra Lab client. This can enable data dashboard, error diagnostic, etc.
A related update to reflect the change: https://github.com/microsoft/HydraLab/pull/637/files
Build and run the app. This integration practice comply with [android-sdk installation](https://learn.microsoft.com/en-us/clarity/mobile-sdk/android-sdk).
*If this is a relatively large or complex change, kick it off by drawing the tech design with PlantUML and explaining why you chose the …
> Add clarity initialization in the MainActivity.java

- agent/src/main/java/com/microsoft/hydralab/agent/runner/analysis/scanner/Scanner.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/analysis/scanner/apk/ApkAnalyzeExecutor.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/analysis/scanner/apk/ApkCanaryExecutor.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/analysis/scanner/apk/ApkLeaksExecutor.java
- center/src/main/java/com/microsoft/hydralab/center/controller/TestTaskController.java
- center/src/main/java/com/microsoft/hydralab/center/service/TestDataService.java
- common/src/main/java/com/microsoft/hydralab/common/entity/common/Task.java
- react/src/component/TasksView.jsx
> Bugfix: count the task state in back-end

- center/deploy_startup/restartMonitorService.sh
- center/deploy_startup/start.sh
Update latest commands of prometheus and pushgateway in restart service script and start.sh.
> Fix Prometheus abnormal data

- center/src/main/java/com/microsoft/hydralab/center/controller/AuthController.java
- center/src/main/java/com/microsoft/hydralab/center/controller/PackageSetController.java
- center/src/main/java/com/microsoft/hydralab/center/controller/StorageController.java
- center/src/main/java/com/microsoft/hydralab/center/controller/TestDetailController.java
- center/src/main/java/com/microsoft/hydralab/center/service/DeviceAgentManagementService.java
- center/src/main/java/com/microsoft/hydralab/center/util/AuthUtil.java
- center/src/main/java/com/microsoft/hydralab/center/util/LocalStorageIOUtil.java
- common/src/main/java/com/microsoft/hydralab/common/util/AttachmentService.java
- common/src/main/java/com/microsoft/hydralab/common/util/LogUtils.java
- hercules/util.py
> BugFix：fix Code QL alerts

- .github/workflows/codeql.yml
- hercules/util.py
> BugFix: fix code ql alert : python regular expression 

- .github/workflows/codeql.yml
- android_client/app/src/main/java/com/microsoft/hydralab/android/client/vpn/HydraLabVpnLogger.kt
> Bugfix: fix code ql alert (kotlin)

- android_client/app/src/main/java/com/microsoft/hydralab/android/client/vpn/HydraLabVpnLoggerTemp.kt
- android_client/app/src/main/java/com/microsoft/hydralab/android/client/vpn/HydraLabVpnQueue.kt
- android_client/app/src/main/java/com/microsoft/hydralab/android/client/vpn/HydraLabVpnService.kt
> CodeQL: rename HydraLabVpnLogger file

- common/src/main/java/com/microsoft/hydralab/common/util/AttachmentService.java
> Bugfix: check the file load type before judging them as the same file

- center/src/main/java/com/microsoft/hydralab/center/util/AuthUtil.java
> Bugfix: Autotype is not supported in safe mode

- gradle_plugin/build.gradle
- gradle_plugin/src/main/groovy/com/microsoft/hydralab/config/TestConfig.java
- gradle_plugin/src/main/groovy/com/microsoft/hydralab/entity/TestTask.java
> Upgrade version of plugin to 1.1.17

- react/src/component/DeviceDialog.jsx
> Increase the refresh interval, sometimes the request time will be > 300ms

- agent/src/main/java/com/microsoft/hydralab/agent/runner/appium/AppiumListener.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/appium/Junit5Listener.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/espresso/EspressoTestInfoProcessorListener.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/maestro/MaestroListener.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/monkey/AdbMonkeyRunner.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/monkey/AppiumMonkeyRunner.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/python/PythonRunner.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/smart/SmartRunner.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/t2c/T2CRunner.java
- agent/src/main/java/com/microsoft/hydralab/agent/runner/xctest/XCTestRunner.java
- center/src/main/java/com/microsoft/hydralab/center/controller/TestTaskController.java
- center/src/main/java/com/microsoft/hydralab/center/service/DeviceAgentManagementService.java
- common/src/main/java/com/microsoft/hydralab/common/entity/common/Task.java
- common/src/main/java/com/microsoft/hydralab/common/entity/common/TestTaskSpec.java
- gradle_plugin/doc/UML/gradle_plugin_yaml_config_design.puml
- gradle_plugin/src/main/groovy/com/microsoft/hydralab/ClientUtilsPlugin.groovy
- gradle_plugin/src/main/groovy/com/microsoft/hydralab/config/TestConfig.java
- gradle_plugin/src/main/groovy/com/microsoft/hydralab/utils/HydraLabAPIClient.java
- gradle_plugin/template/gradle.properties
- gradle_plugin/template/testSpec.yml
This Pull request adds a new test configuration `disableGifEncoder ` having default value as false. It disables the collection of screenshots during the test runs by blocking the calls to  `startGifEncoder `and `stopGifEncoder` methods  when the `disableGifEncoder` is set to true.
> added test spec to disable gif encoder

- gradle_plugin/build.gradle
> [Plugin] Upgrade version to 1.1.19

- agent/src/main/java/com/microsoft/hydralab/agent/socket/AgentWebSocketClient.java
- center/src/main/java/com/microsoft/hydralab/center/service/DeviceAgentManagementService.java
> Bugfix: after the center restarts, the device status may be overwritten

- README.md
- README.zh-CN.md
- docs/index.md
> [Migrate] update pipeline link in doc

- common/src/main/java/com/microsoft/hydralab/common/util/Const.java
> Fix: update the BLOCKED_DEVICE_TIMEOUT to 2 hours to avoid devices gets blocked issue

- center/Dockerfile
- center/build.gradle
- center/deploy_startup/clamAV/clamd.conf
- center/deploy_startup/start.sh
- center/src/main/java/com/microsoft/hydralab/center/controller/PackageSetController.java
- center/src/main/java/com/microsoft/hydralab/center/util/ClamAVScanner.java
Integrate clamAV for uploaded files / attachments scanning
- Test locally in IDE
- Test locally in Docker image
Security enhancement
> [Security update] Integrate clamAV for uploaded files / attachments scanning

- center/src/main/java/com/microsoft/hydralab/center/interceptor/BaseInterceptor.java
- center/src/main/java/com/microsoft/hydralab/center/service/AuthTokenService.java
- react/src/component/HeaderView.jsx
> [Feature] Adapt to Web App Service easyauth

- center/src/main/java/com/microsoft/hydralab/center/interceptor/BaseInterceptor.java
- center/src/main/resources/application.yml
> [Feature] add HYBRID config of api auth mode to support switch in center

- center/src/main/java/com/microsoft/hydralab/center/service/AuthTokenService.java
> Bugfix: Update AuthTokenService to load TeamAdminMap of user

- center/src/main/java/com/microsoft/hydralab/center/util/AuthUtil.java
> Bugfix: mise client is single instance, can't assignLogMessageCallback again
