microsoft/HydraLab

agent/doc/UML/logger_file_design.puml, agent/doc/UML/test_runner_design.puml, agent/src/main/java/com/microsoft/hydralab/agent/config/TestRunnerConfig.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/TestRunner.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/XmlBuilder.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/appium/AppiumCrossRunner.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/appium/AppiumRunner.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/espresso/EspressoRunner.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/espresso/EspressoTestInfoProcessorListener.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/monkey/AdbMonkeyRunner.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/monkey/AppiumMonkeyRunner.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/smart/SmartRunner.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/t2c/T2CRunner.java, agent/src/main/java/com/microsoft/hydralab/agent/service/TestTaskEngineService.java, agent/src/test/java/com/microsoft/hydralab/agent/runner/TestRunnerTest.java, agent/src/test/java/com/microsoft/hydralab/agent/service/TestTaskEngineServiceTest.java, common/src/main/java/com/microsoft/hydralab/common/entity/common/TestTask.java, common/src/main/java/com/microsoft/hydralab/common/logger/impl/ADBLogcatCollector.java
- Test runner lifecycle: buildDeviceTestTask -> setUp -> run -> tearDown
- Remove runner class dependencies for Spring annotations, create TestRunnerConfig.java to centralize the configuration.
- Inline some runner members as local var.
- Change the method access of reInstallApp
- Fix bug in ADBLogcatCollector isCrashFound() method.
=> TestRunner refactor round 2, keep decoupling and build test lifecycle: buildDeviceTestTask -> setUp -> run -> tearDown

README.md
Generate an image of contributors to keep the README.md in sync.
For more details considering contributors image, please head over to [contrib.rocks](https://contrib.rocks/preview?repo=Microsoft%2Fhydralab)
=> Add image of contributors to README

react/src/component/RunnerView.jsx
=> Upgrade front-page to adapt to grant permission and device action

agent/src/main/java/com/microsoft/hydralab/agent/AgentApplication.java, center/src/main/java/com/microsoft/hydralab/center/controller/PackageSetController.java, common/src/main/java/com/microsoft/hydralab/common/entity/common/BlobFileInfo.java, common/src/main/java/com/microsoft/hydralab/common/util/PkgUtil.java, common/src/test/java/com/microsoft/hydralab/common/util/PkgUtilTest.java, taps_to_cases/runner/src/main/java/com/microsoft/hydralab/t2c/runner/ActionInfo.java, taps_to_cases/runner/src/main/java/com/microsoft/hydralab/t2c/runner/DriverInfo.java
[x] Added refactoring and code clean up for java files
=> Added refactoring and code clean up for java files

center/src/main/java/com/microsoft/hydralab/center/service/AgentManageService.java, center/src/test/java/com/microsoft/hydralab/center/service/AgentManageServiceTest.java
Fix directory not existing issue;
Add UT for agent file downloading;
=> Fix directory not existing issue

react/src/component/Dashboard.jsx, react/src/component/HeaderView.jsx, react/webpack.config.js
- Clean up webpack config for dev env
- Replace the https://microsoft.github.io/HydraLab/ entry, since we won't maintain it in a short time.
Here is how the star button looks like:
=> Add star button in the homepage list

common/src/main/java/com/microsoft/hydralab/common/util/ShellUtils.java, common/src/main/java/com/microsoft/hydralab/common/util/TimeUtils.java, common/src/main/java/com/microsoft/hydralab/performance/PerformanceTestManagementService.java, common/src/main/java/com/microsoft/hydralab/performance/inspectors/AndroidBatteryInfoInspector.java, common/src/main/java/com/microsoft/hydralab/performance/inspectors/WindowsBatteryInspector.java, common/src/main/java/com/microsoft/hydralab/performance/inspectors/WindowsMemoryInspector.java, common/src/main/java/com/microsoft/hydralab/performance/parsers/AndroidBatteryInfoResultParser.java, common/src/main/java/com/microsoft/hydralab/performance/parsers/WindowsBatteryResultParser.java, common/src/main/java/com/microsoft/hydralab/performance/parsers/WindowsMemoryResultParser.java, common/src/main/resources/WindowsMemoryInspector.ps1, sdk/src/main/java/com/microsoft/hydralab/agent/runner/TestRunThreadContext.java, sdk/src/main/java/com/microsoft/hydralab/performance/IPerformanceInspectionService.java, sdk/src/main/java/com/microsoft/hydralab/performance/InspectionStrategy.java, sdk/src/main/java/com/microsoft/hydralab/performance/PerformanceInspection.java, sdk/src/main/java/com/microsoft/hydralab/performance/PerformanceInspectionResult.java, sdk/src/main/java/com/microsoft/hydralab/performance/PerformanceInspectionService.java, sdk/src/main/java/com/microsoft/hydralab/performance/PerformanceInspector.java, sdk/src/main/java/com/microsoft/hydralab/performance/PerformanceResultParser.java, sdk/src/main/java/com/microsoft/hydralab/performance/PerformanceTestResult.java
**Changes**
1. Implement WindowsMemoryInspector and WindowsBatteryInspector.
2. Optimize ShellUtils and make all its functions support both powershell and sh.
3. Add WindowsMemoryInspector.ps1 to avoid null output from piped commands when using Runtime.getRuntime().exec().
**TODO**
1. Implement WindowsMemoryResultParser and WindowsBatteryResultParser.
2. Refine WindowsMemoryInspector.ps1 if needed.
=> [Perf] WindowsMemoryInspector and WindowsBatteryInspector

agent/src/main/java/com/microsoft/hydralab/agent/runner/TestRunner.java, common/src/main/java/com/microsoft/hydralab/performance/Entity/AndroidBatteryInfo.java, common/src/main/java/com/microsoft/hydralab/performance/PerformanceTestManagementService.java, common/src/main/java/com/microsoft/hydralab/performance/inspectors/AndroidBatteryInfoInspector.java, common/src/main/java/com/microsoft/hydralab/performance/inspectors/WindowsBatteryInspector.java, common/src/main/java/com/microsoft/hydralab/performance/inspectors/WindowsMemoryInspector.java, common/src/main/java/com/microsoft/hydralab/performance/parsers/AndroidBatteryInfoResultParser.java, common/src/main/java/com/microsoft/hydralab/performance/parsers/WindowsBatteryResultParser.java, common/src/main/java/com/microsoft/hydralab/performance/parsers/WindowsMemoryResultParser.java, sdk/src/main/java/com/microsoft/hydralab/performance/IPerformanceInspectionService.java, sdk/src/main/java/com/microsoft/hydralab/performance/PerformanceInspectionResult.java, sdk/src/main/java/com/microsoft/hydralab/performance/PerformanceInspectionService.java, sdk/src/main/java/com/microsoft/hydralab/performance/PerformanceInspector.java, sdk/src/main/java/com/microsoft/hydralab/performance/PerformanceResultParser.java, sdk/src/main/java/com/microsoft/hydralab/performance/PerformanceTestResult.java
- Implement AndroidBatteryInfoInspector
- Implement AndroidBatteryInfoResultParser
- Refine performance framework
- Raw result file
- Sample of parsed info
```
AndroidBatteryInfo(
appPackageName=com.microsoft.appmanager, 
timeStamp=1675930618251, 
cpu=0.00432, 
screen=0.0, 
wakeLock=0.0,
systemService=0.0,
wifi=0.0, 
appUsage=0.00432,
total=0.948, 
ratio=0.004556962, 
description=test battery2
)
```
=> [Perf] Implement AndroidBatteryInfoInspector and AndroidBatteryInfoResultParser

common/src/main/java/com/microsoft/hydralab/performance/parsers/AndroidBatteryInfoResultParser.java
warning: [try] explicit call to close() on an auto-closeable resource: in.close();
=> Fix lint warning in AndroidBatteryInfoResultParser

center/src/main/java/com/microsoft/hydralab/center/service/DeviceAgentManagementService.java
if the group type is all and someone of them is under testing, the status of free device would be set as testing, but the task wouldn't start.
Repro steps:
1. trigger first task with grouptype SINGLE
2. when the first task is running, trigger second task with grouptype ALL
3. the second task would be added to queue but the status of rest devices has been set to testing...
=> Bugfix: Set the status of devices to testing after the task is sure to run.

taps_to_cases/runner/src/main/java/com/microsoft/hydralab/t2c/runner/T2CAppiumUtils.java
Add page source content from webdriver when T2C fails the test case.
=> Add page source info in error when T2C fails test

react/src/component/Dashboard.jsx, react/src/component/DeviceGroupView.jsx, react/src/component/GroupManageView.jsx
=> change "Group Management" to "Device Group"

taps_to_cases/runner/src/main/java/com/microsoft/hydralab/t2c/runner/T2CAppiumUtils.java, taps_to_cases/runner/src/main/java/com/microsoft/hydralab/t2c/runner/T2CJsonParser.java, taps_to_cases/runner/src/main/java/com/microsoft/hydralab/t2c/runner/controller/AndroidDriverController.java, taps_to_cases/runner/src/main/java/com/microsoft/hydralab/t2c/runner/controller/BaseDriverController.java, taps_to_cases/runner/src/main/java/com/microsoft/hydralab/t2c/runner/controller/EdgeDriverController.java, taps_to_cases/runner/src/main/java/com/microsoft/hydralab/t2c/runner/controller/WindowsDriverController.java, taps_to_cases/runner/src/main/java/com/microsoft/hydralab/t2c/runner/elements/AndroidElementInfo.java, taps_to_cases/runner/src/main/java/com/microsoft/hydralab/t2c/runner/elements/BaseElementInfo.java, taps_to_cases/runner/src/main/java/com/microsoft/hydralab/t2c/runner/elements/WindowsElementInfo.java, taps_to_cases/runner/src/main/java/com/microsoft/hydralab/t2c/runner/finder/AndroidElementFinder.java, taps_to_cases/runner/src/main/java/com/microsoft/hydralab/t2c/runner/finder/EdgeElementFinder.java, taps_to_cases/runner/src/main/java/com/microsoft/hydralab/t2c/runner/finder/ElementFinder.java, taps_to_cases/runner/src/main/java/com/microsoft/hydralab/t2c/runner/finder/ElementFinderFactory.java, taps_to_cases/runner/src/main/java/com/microsoft/hydralab/t2c/runner/finder/WindowsElementFinder.java, taps_to_cases/runner/src/test/java/com/microsoft/hydralab/t2c/runner/MockDriverT2CTest.java, taps_to_cases/runner/src/test/java/com/microsoft/hydralab/t2c/runner/SampleT2CTest.java
1. Following best practice of FastJson, annotate `AndroidElementInfo`
2. `BaseDriverController` should not expose any details inside, for example access to `webDriver` is not good to me.
3. Refactor `findElement` method with factory pattern, support dynamic registration and default factories of current existing controllers.
4. In this PR, we minimize the change in the finder package when changes on element search, no code changes should happen in controller classes, controller should only be responsible for decoration of `WebDriver` (Our `drivercontroller` is a decoration of `WebDriver`
5. In this PR, `ElementInfo` will not be aware of any info about how to find itself in page, which is not its responsibility. They are pure POJO classes.
=> Refactor T2C runner about "findElment"

agent/build.gradle, build.gradle, common/src/main/java/com/microsoft/hydralab/common/entity/common/TestTask.java, quality/checkstyle-ruleset.xml, quality/checkstyle-suppressions.xml, quality/checkstyle.gradle, taps_to_cases/runner/src/main/java/com/microsoft/hydralab/t2c/runner/ActionInfo.java
1. Configure xlint for all java modules in HydraLab
2. Integrate checkstyle plugin
TODO:
1. Format all java codes by checkstyle gradle task.
2. Set up githook if necessary.
PS. android_client is not included in this PR.
=> Apply xlint in java compiler args and integrate checkstyle plugin

common/src/main/java/com/microsoft/hydralab/performance/Entity/AndroidMemoryInfo.java, common/src/main/java/com/microsoft/hydralab/performance/PerformanceTestManagementService.java, common/src/main/java/com/microsoft/hydralab/performance/inspectors/AndroidMemoryInfoInspector.java, common/src/main/java/com/microsoft/hydralab/performance/parsers/AndroidMemoryInfoResultParser.java, sdk/src/main/java/com/microsoft/hydralab/performance/PerformanceInspection.java
Add parser and inspector of memory info in Android, not the snapshot of JVM, but some metadata of JVM. For example, size of PSS, heap size, etc.
=> Add android meminfo inspector and parser

vsts_extension/Tasks/HydraLabDeployTest/hydra-lab-deploy-test.ts, vsts_extension/Tasks/HydraLabDeployTest/task.json, vsts_extension/vss-extension.json
Fix: ADO plugin report url can't redirect
=> Fix: ADO plugin report url can't redirect

agent/src/main/java/com/microsoft/hydralab/agent/runner/monkey/AdbMonkeyRunner.java
Trigger a ADB Monkey with test config {"config":"--throttle 100 -v -v"}
=> BugFix: the args of adbMonkey should be ahead of click times

common/src/main/java/com/microsoft/hydralab/common/util/MachineInfoUtils.java, common/src/main/java/com/microsoft/hydralab/performance/inspectors/WindowsBatteryInspector.java, common/src/main/java/com/microsoft/hydralab/performance/parsers/WindowsBatteryResultParser.java, common/src/main/java/com/microsoft/hydralab/performance/parsers/WindowsMemoryResultParser.java, common/src/main/resources/DetectWindowsLaptop.ps1, common/src/main/resources/WindowsBatteryInspector.ps1, common/src/main/resources/WindowsMemoryInspector.ps1
1. Fix the compatibility issue that WindowsBatteryInpector.ps1 cannot be executed with Runtime class.
2. Add null check for each inspectionResult item in the for loop of parsers.
No.
Windows Perf is still in progress, no need to test for now.
=> [Perf] Fix the compatibility issue that WindowsBatteryInpector.ps1 cannot be executed with Runtime class

common/src/main/java/com/microsoft/hydralab/common/util/ADBOperateUtil.java, common/src/main/java/com/microsoft/hydralab/common/util/Const.java, common/src/main/java/com/microsoft/hydralab/common/util/LogUtils.java, common/src/test/java/com/microsoft/hydralab/common/util/StringUtilsTest.java
Fix the  regex bug. For Linux file names, there are almost no restrictions - apart from '/' and '\0', you're allowed to use anything. So adding more allowed options will help correctly identify the path.
Add UT
=> Fix the linux path check bug, and add UT

react/src/component/PerfTestDashboard.jsx
Add a new chart for Windows memory performance test.
Testing with the following json parameter:
"inspectionStrategies": [
{
"strategyType": "TEST_SCHEDULE",
"interval": 5000,
"intervalUnit": "MILLISECONDS",
"inspection": {
"inspectorType": "INSPECTOR_WIN_MEMORY",
"appId": "com.microsoft.hydralab.android.client",
"description": "testschedule"
}
}
]
=> [Perf] Add a new chart for Windows memory performance test in Test Report

agent/agent_installer/MacOS/iOS/installer.sh
Update make it easier for user to install agent on MacOS.
Tested on my MacOS. This is hard to test. So we might need to figure out a way for testing and ensuring the quality of the script, this `installer.sh` is a part of the user experience as well and we need to make sure its accountability.
=> Update installer.sh to support the ANDROID_HOME env automation

center/src/main/java/com/microsoft/hydralab/center/controller/StorageController.java, common/src/main/java/com/microsoft/hydralab/common/util/Const.java
According to https://cloud.tencent.com/developer/section/1189916, file name as input should include no ";", otherwise file name will be cut down to the first part of the file name before";".
Locally tested, the updated regex is working.
=> Add validation for ";" in file name for LOCAL storage upload/download

agent/src/main/java/com/microsoft/hydralab/agent/runner/xctest/XCTestRunner.java
=> Add frame to XCTest gif

gradle_plugin/build.gradle, gradle_plugin/src/main/groovy/com/microsoft/hydralab/ClientUtilsPlugin.groovy, gradle_plugin/src/test/java/com/microsoft/hydralab/ClientUtilsPluginTest.java
- Version upgraded to 1.1.5;
The param hydraLabAPIHost in log showed as hydraLabAPIhost, which may confuse users.
Log change, not tested
=> Fix gradle plugin log typo

agent/src/main/java/com/microsoft/hydralab/agent/runner/monkey/AdbMonkeyRunner.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/monkey/AppiumMonkeyRunner.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/smart/SmartRunner.java, common/src/main/java/com/microsoft/hydralab/common/entity/common/TestRun.java, common/src/main/java/com/microsoft/hydralab/performance/PerformanceTestManagementService.java, react/src/component/PerfTestDashboard.jsx, sdk/src/main/java/com/microsoft/hydralab/agent/runner/ITestRun.java, sdk/src/main/java/com/microsoft/hydralab/performance/PerformanceInspectionResult.java
Run the perf test and check the perf dashboard at HydraLab portal
=> [Perf] Add test case name and description to the performance test chart

common/src/main/java/com/microsoft/hydralab/common/entity/common/PerformanceTestResultEntity.java, common/src/main/java/com/microsoft/hydralab/performance/parsers/AndroidBatteryInfoResultParser.java, react/src/component/PerfTestDashboard.jsx
Trigger E2E performance test and check the test report
=> [Fix] Fix undefine parsed data and invalid date

agent/src/main/java/com/microsoft/hydralab/agent/runner/t2c/T2CRunner.java, common/src/main/java/com/microsoft/hydralab/common/management/AppiumServerManager.java, common/src/main/java/com/microsoft/hydralab/common/management/device/impl/IOSDeviceDriver.java, common/src/main/java/com/microsoft/hydralab/common/util/IOSPerfTestHelper.java, common/src/main/java/com/microsoft/hydralab/common/util/IOSUtils.java, taps_to_cases/runner/build.gradle, taps_to_cases/runner/src/main/java/com/microsoft/hydralab/t2c/runner/controller/IOSDriverController.java
=> Start WDA proxy if we need ios driver before test start

center/src/main/java/com/microsoft/hydralab/center/service/DeviceAgentManagementService.java, center/src/main/java/com/microsoft/hydralab/center/socket/CenterDeviceSocketEndpoint.java, center/src/test/java/com/microsoft/hydralab/center/service/DeviceAgentManagementServiceTest.java, center/src/test/java/com/microsoft/hydralab/center/test/BaseTest.java, sdk/.gitignore
**A few words to explain your changes**:  refactor center onMessage, and create UT
=> refactor center onMessage, and create UT

common/src/main/java/com/microsoft/hydralab/performance/entity/IOSEnergyGaugeInfo.java, common/src/main/java/com/microsoft/hydralab/performance/entity/IOSMemoryPerfInfo.java, common/src/main/java/com/microsoft/hydralab/performance/parsers/IOSEnergyGaugeResultParser.java, common/src/main/java/com/microsoft/hydralab/performance/parsers/IOSMemoryPerfResultParser.java, sdk/src/main/java/com/microsoft/hydralab/performance/IBaselineMetrics.java
=> [Perf] Implement perf summary and history for iOS performance test

agent/src/main/java/com/microsoft/hydralab/agent/service/DeviceControlService.java
=> Bugfix: update the action of getting screenshot from sync to async to avoid process blocking

center/src/main/java/com/microsoft/hydralab/center/controller/TestDetailController.java, react/src/component/TestReportView.jsx
=> Bugfix: handle the scene of file not exist

react/src/component/PerfTestDashboard.jsx, react/src/component/TestReportView.jsx
- Add device info to the Perf dashboard
- Fix the bug of display confusion when more than two runs in a test task.
=> [Front-end] [Perf] Add device info to the Perf dashboard

agent/src/main/java/com/microsoft/hydralab/agent/runner/TestRunDeviceOrchestrator.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/TestRunner.java, common/src/main/java/com/microsoft/hydralab/common/screen/WindowsScreenRecorder.java
=> Bugfix: Fix the bug of screen recorder not stopped when task is canceled

agent/src/main/java/com/microsoft/hydralab/agent/runner/appium/AppiumRunner.java, center/src/main/java/com/microsoft/hydralab/center/service/TestTaskService.java, center/src/main/java/com/microsoft/hydralab/center/socket/CenterDeviceSocketEndpoint.java, common/src/main/java/com/microsoft/hydralab/common/management/AppiumServerManager.java
1. add another method to verify the status of windows driver because the method would throw exception when the type of driver is iOS
2. catch all of the exception when exec the testing jar file
3. catch the exception of SerializeUtil.byteArrToMessage
4. add a log to locate issue
*If this is a relatively large or complex change, kick it off by drawing the tech design with PlantUML and explaining why you chose the solution you did and what …
=> Bugfix: add another method to verify the status of windows driver

agent/src/main/java/com/microsoft/hydralab/agent/command/DeviceScriptCommandLoader.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/ActionExecutor.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/TestRunDeviceOrchestrator.java, agent/src/test/java/com/microsoft/hydralab/agent/runner/ActionExecutorTest.java, agent/src/test/java/com/microsoft/hydralab/agent/runner/CommandActionLoaderTest.java, common/src/main/java/com/microsoft/hydralab/common/util/Const.java
- Remove Windows restriction for command running on Agents.
- Add AGENT type for the list of deviceActions to run on an agent separately, rather than being run together with commands for all or mobile devices (to ensure being run only once per test).
Tested locally. See screenshot as below
*If this is a relatively large or complex change, kick it off by drawing the tech design with PlantUML and explaining why you chose the solution you did and …
=> Feat.: support Linux command running during tests

center/src/main/java/com/microsoft/hydralab/center/openai/AzureOpenAIServiceClient.java, center/src/main/java/com/microsoft/hydralab/center/openai/ChatMessage.java, center/src/main/java/com/microsoft/hydralab/center/openai/ChatRequest.java, center/src/test/java/com/microsoft/hydralab/center/openai/AzureOpenAIServiceClientTest.java, center/src/test/java/com/microsoft/hydralab/center/test/BaseTest.java
**A few words to explain your changes**:  Provide a client for Azure OpenAI GPT model service. Only add the code, no function attached.
=> Provide a client for Azure OpenAI GPT model service

common/src/main/java/com/microsoft/hydralab/common/screen/ADBScreenRecorder.java, common/src/main/java/com/microsoft/hydralab/common/screen/FFmpegConcatUtil.java
- ADBScreenRecorder finishRecording waits less time (120s -> 30s);
- ADBScreenRecorder modifies process stream receiving logic to avoid blocking;
- Added some logs;
=> Fix ADBScreenRecorder blocking issue in docker images

agent/src/main/java/com/microsoft/hydralab/agent/runner/appium/AppiumListener.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/appium/AppiumRunner.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/appium/Junit5Listener.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/espresso/EspressoTestInfoProcessorListener.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/monkey/AdbMonkeyRunner.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/monkey/AppiumMonkeyRunner.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/smart/SmartRunner.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/t2c/T2CRunner.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/xctest/XCTestRunner.java, common/src/main/java/com/microsoft/hydralab/common/entity/common/TestTask.java, common/src/main/java/com/microsoft/hydralab/common/entity/common/TestTaskSpec.java
**Linked GitHub issue ID**: #281 
No recording video file generated when the `disableRecording` is `true`
=> Add disabling recording option for a test run to avoid OOM for tests with a long test time

common/src/main/java/com/microsoft/hydralab/common/util/ADBOperateUtil.java
**A few words to explain your changes**:  Fix a error reported by coworkers
```
va:290)[WebSocketConnectReadThread-17] - Metric of agent running test task number has been registered.
2023-06-08 23:55:38,466 ERROR (c.m.h.c.u.ADBOperateUtil - ADBOperateUtil.java:79)[WebSocketConnectReadThread-17] - Error when changing the value of AndroidDebugBridge sSocketAddr
java.net.UnknownHostException: host.docker.internal: Name or service not known
at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
at …
```
=> Fix error handling logic of changeADBSocketHostAddr

agent/src/main/java/com/microsoft/hydralab/agent/scheduled/ScheduledDeviceControlTasks.java, agent/src/main/resources/logback-common.xml
=> Bugfix: clear history files to free up disk space

android_client/app/src/main/AndroidManifest.xml
We update client app in release 15.* version.
This break storage function in old Android < 11.
see this article: https://developer.android.com/about/versions/11/privacy/storage
=> Fix Legacy Storage Issue

center/src/main/java/com/microsoft/hydralab/center/controller/AuthController.java, center/src/main/java/com/microsoft/hydralab/center/interceptor/BaseInterceptor.java, common/src/main/java/com/microsoft/hydralab/common/util/Const.java
Add swagger doc api path for oauth redirect.
=> Add swagger doc api path for oauth redirect

agent/src/main/java/com/microsoft/hydralab/agent/runner/monkey/AdbMonkeyRunner.java
Fix the following issue:
- Crash is not thrown by ADB and only recorded in logcat, which not eventually result in test failure, and video cannot be stored correctly.
=> Fix: some crashs are not thrown by ADB and only recorded in logcat, which not eventually result in test failure, and video cannot be stored correctly

react/src/component/RunnerView.jsx, react/src/component/TestReportView.jsx
=> Feature: download all test result files from page

common/src/main/java/com/microsoft/hydralab/common/screen/IOSAppiumScreenRecorderForMac.java
A minor fix for the sleep time between `startRecordingScreen`. The `retryAndSleepWhenFalse` takes sleepSeconds param and it's set to 1000 second (probably a mistake). I changed the value to 10 second (align with the other usages of this method).
I encounter an issue running test on a mac machine. If appium failed to start the recording the `retryAndSleepWhenFalse` enter a very long sleep of 1000 seconds which block the test. Changing the value to 10 second (align with the other usages of this method) did fix the issue.
=> Fix sleep between retries of startRecordingScreen

center/src/main/java/com/microsoft/hydralab/center/service/DeviceAgentManagementService.java
=> Bugfix: update center device status and list totally

common/src/main/java/com/microsoft/hydralab/common/entity/center/AgentDeviceGroup.java, common/src/main/java/com/microsoft/hydralab/common/entity/common/AnalysisTask.java, common/src/main/java/com/microsoft/hydralab/common/entity/common/TaskResult.java, common/src/main/java/com/microsoft/hydralab/common/entity/common/scanner/ApkManifest.java, common/src/main/java/com/microsoft/hydralab/common/entity/common/scanner/ApkReport.java, common/src/main/java/com/microsoft/hydralab/common/entity/common/scanner/ApkSizeReport.java, common/src/main/java/com/microsoft/hydralab/common/entity/common/scanner/BuildInfo.java, common/src/main/java/com/microsoft/hydralab/common/entity/common/scanner/LeakInfo.java
=> Bugfix: update the column type to adapt to SqlServer

agent/src/main/java/com/microsoft/hydralab/agent/util/FileLoadUtil.java, center/src/main/java/com/microsoft/hydralab/center/service/DeviceAgentManagementService.java
=> Bugfix: reset available count when canceling Analysis Task

center/src/main/java/com/microsoft/hydralab/center/service/TestDataService.java, common/src/main/java/com/microsoft/hydralab/common/entity/common/Task.java
=> Bugfix: Handle deprecated fields to adapt to history versions of Gradle & Azure plugin

center/src/main/java/com/microsoft/hydralab/center/service/DeviceAgentManagementService.java, react/src/component/TasksView.jsx
=> Bugfix: add null verify to adapt previous version agent & update front-page

center/src/main/java/com/microsoft/hydralab/center/controller/AuthController.java, center/src/main/java/com/microsoft/hydralab/center/util/AuthUtil.java, center/src/main/resources/application.yml, common/build.gradle, common/src/main/java/com/microsoft/hydralab/common/file/impl/azure/AzureBlobClientAdapter.java, common/src/main/java/com/microsoft/hydralab/common/file/impl/azure/AzureBlobProperty.java, common/src/main/java/com/microsoft/hydralab/common/file/impl/azure/SASData.java, common/src/main/java/com/microsoft/hydralab/common/file/impl/azure/SASPermission.java, common/src/test/java/com/microsoft/hydralab/common/file/azure/BlobClientTest.java
1. Switch access token to id token
2. disable blob local auth and merge 6 blobs to 1
=> Disable AAD and Azure Blob local auth

README.zh-CN.md, center/application-sample.yml, center/build.gradle, center/src/main/resources/application-docker.yml, center/src/main/resources/application-release.yml, center/src/main/resources/application-test.yml, center/src/main/resources/application.yml, common/build.gradle
Enable Managed Identity authentication on Azure by doing the following:
- Updated DB Connection String
- Move redundant username/password from basic env yml to specific envs
Tested locally with local account, allocating the same permissions in DB and run the app without error.
=> Fix SQL Server connection with removing username/secret

agent/src/main/java/com/microsoft/hydralab/agent/runner/TestRunDeviceOrchestrator.java
=> Bugfix: rename the video name when test device count is 1

center/src/main/java/com/microsoft/hydralab/center/service/DeviceAgentManagementService.java, center/src/test/java/com/microsoft/hydralab/center/service/DeviceAgentManagementServiceTest.java, common/src/main/java/com/microsoft/hydralab/common/entity/common/BlockedDeviceInfo.java, common/src/main/java/com/microsoft/hydralab/common/repository/BlockedDeviceInfoRepository.java, gradle_plugin/src/main/groovy/com/microsoft/hydralab/utils/HydraLabClientUtils.java
The PR aims to save the blocked Device Information in a BlockedDeviceInfoRepository Database to persist it across sessions even if the center gets restarted or the connection between the agent and server is lost due to network problems. 
- `common/src/main/java/com/microsoft/hydralab/common/repository/BlockedDeviceInfoRepository.java`: Added Repository to save blocked device information in the database.
- `gradle_plugin/src/main/groovy/com/microsoft/hydralab/utils/HydraLabClientUtils.java`: Fixed syntax error / formatting issue.
- `common/src/main/java/com/microsoft/hydralab/common/entity/common/BlockedDeviceInfo.java`: Made it an Entity and added table annotations with primary key to store the blockedDeviceInfo in the Database.
- …
=> Save Blocked Device Information in BlockedDeviceInfoRepository for persistence and fix formatting error

center/src/main/java/com/microsoft/hydralab/center/controller/TestTaskController.java, center/src/main/java/com/microsoft/hydralab/center/service/DeviceAgentManagementService.java, center/src/main/java/com/microsoft/hydralab/center/service/TestTaskService.java
…sk would be added to queue and wait corn to unblock
=> Bugfix: If unblock failed and all devices in a group were blocked, task would be added to queue and waiting for cron to unblock

agent/src/main/java/com/microsoft/hydralab/agent/runner/TestRunner.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/appium/AppiumListener.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/appium/AppiumRunner.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/appium/Junit5Listener.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/espresso/EspressoRunner.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/espresso/EspressoTestInfoProcessorListener.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/maestro/MaestroListener.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/maestro/MaestroRunner.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/monkey/AdbMonkeyRunner.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/monkey/AppiumMonkeyRunner.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/python/PythonRunner.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/smart/SmartRunner.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/t2c/T2CRunner.java, agent/src/main/java/com/microsoft/hydralab/agent/runner/xctest/XCTestRunner.java
This Pull request  makes use of `disableGifEncoder `  to avoid calls to `addGifFrameAsyncDelay` to completely prevent any capture of Screenshots.  It disables the collection of screenshots during the test runs when `disableGifEncoder ` is set to true.
=> Stop calls to addGifFrameAsyncDelay to prevent collection of screenshots

center/src/main/java/com/microsoft/hydralab/center/controller/TeamController.java, center/src/main/java/com/microsoft/hydralab/center/interceptor/BaseInterceptor.java, center/src/main/java/com/microsoft/hydralab/center/repository/TeamAppRelationRepository.java, center/src/main/java/com/microsoft/hydralab/center/service/AuthTokenService.java, center/src/main/java/com/microsoft/hydralab/center/service/TeamAppManagementService.java, center/src/main/java/com/microsoft/hydralab/center/util/AuthUtil.java, center/src/main/resources/application.yml, common/src/main/java/com/microsoft/hydralab/common/entity/center/TeamAppRelation.java, common/src/main/java/com/microsoft/hydralab/common/entity/center/TeamAppRelationId.java, react/src/component/TeamAppRegistrationManagement.jsx, react/src/component/TeamManagement.jsx
- Enable app registration auth approach for pipeline requests, according to SFI requirement.
- Add portal UI for app registration client ID linking:
- <img width="2552" height="1305" alt="image" src="https://github.com/user-attachments/assets/23f0f815-a5db-438b-88d8-facb4a5c3d7e" />
The pipeline needs to switch to App registration token authentication approach, basic additional steps:
- Generate ADO Service Connection for App Registration automatically
- Add `API permission` for resource api://228c4d51-5002-4fcf-8752-552b478fff77 in the App Registration
- Onboard AR client ID on Hydra Lab portal and create relationship to team ID
- Add precedent AAD token acquiring task in test …
=> Feature: enable app registration

azure-pipelines-ci.yml, center/build.gradle, center/src/main/java/com/microsoft/hydralab/center/util/AuthUtil.java, center/src/main/resources/application-release.yml
=> Feature: support MISE mode to valid token

.gitignore, azure-pipelines-ci.yml, center/Dockerfile_MISE, center/build.gradle, center/src/main/java/com/microsoft/hydralab/center/util/AuthUtil.java, center/src/main/resources/application-release.yml
=> Fature: adapt to MISE container mode
